#!/bin/bash
# Start and enable Apache to run on
systemctl start httpd
systemctl enable httpd

# Crea an index.html file with CSS animations for background color changing
cat > Lyar/www/html/index.html <<'EOF'
< DOCTYPE html>
<html>
‹head>
    ‹meta charset="UTF-8">
    ‹title>Custom AMI Instance</title>
    <style>
        @keyframes backgroundChange {
            0% { background-color: #6495ED; }
            50% { background-color: #ADD8E6; }
            100% { background-color: #6495ED; }
        }

        body {
            color: white; 
            font-size: 48px; 
            display: flex;
            justify-content: center; 
            align-items: center;
            height: 100vh;
            margin: 0;
            animation: backgroundChange 4s infinite;
        }
    </style>
</head> 
</body> </html>
    ‹div>This Instance Was Launched from a Custom AMI</div>
</body>
</html>
EOF

# Ensure the httpd service is correctly set up to start on boot
chkconfig httpd on
